obj-$(CONFIG_VIDEO_FIMC)	+= fimc/
obj-$(CONFIG_VIDEO_JPEG)	+= jpeg/
obj-$(CONFIG_VIDEO_TVOUT)	+= tvout/
obj-$(CONFIG_VIDEO_FIMG2D)	+= fimg2d_android/
obj-$(CONFIG_VIDEO_MFC5X)	+= mfc5x/
obj-$(CONFIG_VIDEO_MALI400MP)	+= mali/
obj-$(CONFIG_VIDEO_UMP)		+= ump/

EXTRA_CFLAGS += -Idrivers/media/video

